CONTAINER Octsplinify
{
	NAME Octsplinify;
	INCLUDE Obase;

	GROUP ID_OBJECTPROPERTIES
	{
		REAL CTTSPOBJECT_MAXSEG { UNIT METER;	MIN 0.0; CUSTOMGUI REALSLIDER; STEP 0.01; MINSLIDER 0.0; MAXSLIDER 100.0;}
		LONG CTTSPOBJECT_WINDOW { MIN 1; MAX 100; CUSTOMGUI LONGSLIDER; }
		BOOL CTTSPOBJECT_REL {}

		IN_EXCLUDE TRACE_ELEMENTS {ACCEPT {Obase; } }

	}

INCLUDE Osplineprimitive;
}
